<?php

/**
 * Test class for DataSource.
 * Generated by PHPUnit on 2011-12-30 at 15:50:50.
 */
class DataSourceTest extends EMongoDbTestCase
{

    public $fixtures = array(
        'ds' => 'DataSource',
        'users' => 'User'
    );

    /**
     * @var DataSource
     */
    protected $object;

    /**
     * @todo Implement testRules().
     */
    public function testRules()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
